### ISSUE TITLE
Independence from the starting directory

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#12]
When `post4` binary is started as `./src/post4`, it cannot find the file `post4.p4`:

```screenlog
./src/post4
post4: post4.p4: No such file or directory
ok
```

But if we are in the `src` directory, it works:
```screenlog
./post4
ok
```

Can `post4` obtain its binary image location from the OS and try to find the file `post4.p4` from this location?

**Comment by SirWumpus** [comment]
You could do a `make install` in which case `post4` is copied to `/usr/local/bin/` and `post4.p4` to `/usr/local/lib/post4/`.

Alternatively you could:

        ./src/port4 -c ./src/post4.p4

or you could `export POST4_PATH=...`, eg.

        export POST4_PATH="$(pwd)/src"
        src/post4

**Comment by SirWumpus** [comment]
The built-in default `POST4_PATH` can be shown with `post4 -V`; it can be altered at compile time if the default is not ideal.

**Comment by SirWumpus** [comment]
Closed given the existing methods to specify word definitions file, `post4.p4`.
