### ISSUE TITLE
Tick should throw an exception on notfound

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#13]
At the moment, the word `[']` and `'` (Tick) returns `0` if its immediate argument is not found.

Typically, Forth systems throw an exception in this case, and it's the expected behavior. In the future versions of the standard it will be required to throw -13 in this case (in the frame of eliminating ambiguous conditions).

**Comment by SirWumpus** [comment]
The solution I opted for here was to redefine `'` and `[']` again once `THROW` is defined in `post4.p4`.  

Personally I would have like to only define these once, but there is a circular dependency such that you need to define basic versions for use in words like `IF` that is used by `THROW`.  (Sometimes Forth does my head in.)
