### ISSUE TITLE
`:noname` shall return xt

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#15]
https://github.com/SirWumpus/post4/blob/93efbaf8a55d18f2763f7157b721f308b7cfce03/src/post4.c#L1791-L1793

`:noname ( -- xt colon-sys )` shall leave _xt_ (along with optional _colon-sys_) on the stack.  In this case it is done by `;` (Semicolon). It's incorrect.

A test case (should be run on the empty data stack):
```forth
t{ depth -> 0 }t
t{ :noname  ( +n -- i*n ) dup if dup 1- [ depth 1- pick compile, ] then ; 3 swap execute -> 3 2 1 0 }t
```

**Comment by SirWumpus** [comment]
Some times I think you come up with these things just to mess with my reality and warp my brain; I can feel it turning into some sort of 9th dimensional mobius loop.

**Comment by ruv** [comment]
> Some times I think you come up with these things just to mess with my reality and warp my brain

My apologies 🤗    It was the first test case that came to my mind.

**Comment by SirWumpus** [comment]
> > Some times I think you come up with these things just to mess with my reality and warp my brain
> 
> My apologies 🤗 It was the first test case that came to my mind.

Its all good.  I actual enjoy it (after my brain stops banging itself against my inner skull) the puzzle aspects.  You always manage to present interesting and fascinating examples of the subtleties of many Forth words.
