### ISSUE TITLE
Some exceptions cannot be cought

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#21]
Some examples:

```forth
s" include nonexistent-file.fth" ' evaluate catch .( error: ) . cr

1 0 ' / catch .
```
They do not print what is expected.

Probably, in `_thrown`, you need to transfer control to the Forth `throw` word.  Something like:
```c
  if ( _catch_frame != 0 ) {
      P4_PUSH(ctx->ds, (P4_Int) rc )
      exec[0].w = word_throw ; // xt of `throw`
      ip = exec;
      NEXT;
  }
```

But you need to know the xt of `throw`, and `_catch_frame` address (or make it a part of ctx).

**Comment by SirWumpus** [comment]
I have a fix for this.  Just waiting on closure of #18 (and #20 maybe).

**Comment by SirWumpus** [comment]
**SIDEBAR**: Why does `INCLUDE-FILE` not return `ior` like ***all*** the other File operation words?  Its is the only one that does not.  Instead it appears to punt.  Doesn't even specify explicit exceptions to return via `CATCH` `THROW`.  In a hosted POSIX environment it would make sense to return `errno` (which are positive values) as the `ior`, which are system define; `THROW`ing `errno` works too, but there does not appear to be clear statement about this and no clear mapping of all the `errno` to exceptions (P4_THROW_ENOENT, P4_THROW_EIO).

I assume `INCLUDE` and `INCLUDED` are implemented using `INCLUDE-FILE` (or equivalent).

**Comment by ruv** [comment]
> Why does `INCLUDE-FILE` not return ior like **all** the other File operation words?

I think, it is because:
  1. `include-file` can consume and produce any number of additional stack parameters (just like `evaluate);
  2. an I/O error can occur in a nested `read-file` or `read-line`;
  3. `include-file` must be _implementable_ without catch/throw (since the **Exception word set** was optional);
  4. anyway, a program cannot easily handle the returned ior (except logging), but can only re-throw the exception, which is impossible without catch/throw.

Other Forth words that return ior consume a fixed number of stack parameters, and the stack effect and internal state are sufficiently specified in case of an error. So, the returned ior can be easily handled without catch/throw.

On the other hand, I don't see much benefit that  the `include-file` word brings to programs. A possible scenario is for a program to open a file using `open-file`, read part of the file using `read-file`, and then interpret the rest of the file using `include-file`.  And what a practical use case for that? Skipping the BOM?

A Forth system probably implements this word only as a natural factor of `included`.

**Comment by SirWumpus** [comment]
> I don't see much benefit that the include-file word brings to programs.

I suspect `INCLUDE-FILE` is meant to be the equivalent of `LOAD` for streams.

**Comment by ruv** [comment]
> I suspect `INCLUDE-FILE` is meant to be the equivalent of `LOAD` for streams.

But there are no means to open a stream such as a pipe or socket. If they are supported, they can be `included` using special names like `pipe:///...` or `socket:///...`. There is no need for `include-file`.

A possible use case for `include-file` is probably when a fileid of a pipe is passed from one process to another process (e.g., from the parent process to a child process).  But this requires some additional system-specific facilities anyway.

In **some** implementations `include-file` can be also used by `quit` to interpret the standard input (probably it should not close the handle on error when it is stdin).

**Comment by SirWumpus** [comment]
Actually I'd use `OPEN-FILE` for any type of file returning a `fd` like `pipe:` and `socket:` (the `//` in a URI have special meaning that I don't think would apply, certainly not pipes).  Then `INLCUDED` would be much like before.

> In some implementations `include-file` can be also used by `quit` to interpret the standard input 

Eww.  I don't see how that would work or make sense given the relationship of pipes to stdin/stdout in other languages.
