### ISSUE TITLE
Switch File Access words from C streaming I/O to low level POSIX I/O.

### ISSUE THREAD

**Issue by SirWumpus** [SirWumpus/post4#27]
The current implementation of the File Access word set uses the C file stream API, ie. `fopen`, `fclose`, `fread`, `fwrite`, etc.  So currently a `fileid` is actually a C `FILE *`.  Consider switching to POSIX File I/O functions `open`, `close`, `read`, `write`, etc. where a `fileid` is a `file descriptor` aka `fd`.  One of the benefits for the Streaming I/O is the buffering; however with POSIX file I/O it would be possible to implement Forth based streaming buffered I/O.  

* With POSIX File I/O, consider moving the Block word set from C to Forth words.
* Add support for Socket I/O, ie. `socket`, `connect`, `accept`, etc. Sockets typically use `read`, `write`, `close`, etc. which can be shared with the File Access words.

**Comment by ruv** [comment]
Note: C provides `fgets`, a method to read a line. Using POSIX `read`, you have to implement buffering for `read-line` to avoid file repositioning (I did it in Forth).

**Comment by SirWumpus** [comment]
> Note: C provides `fgets`, a method to read a line. Using POSIX `read`, you have to implement buffering for `read-line` to avoid file repositioning (I did it in Forth).

Yes.

C file streams certainly have a certain advantage, which is why I opted for that with the File Access words (plus the C API is portable).  I had considered implementing the Block words using `fread` and `fwrite` since under the hood it would drill down to POSIX `read` and `write`. (Hmmm.  Maybe I should reconsider Block I/O using file stream API.  Little over kill.)

How complex was a Forth `READ-LINE`?

**Comment by ruv** [comment]
> How complex was a Forth `READ-LINE`?

The core part is a buffered stream, which is pretty simple ([1](https://github.com/rufig/spf4-utf8/blob/master/devel/~pinka/model/io/buffer-rw.immutable.f.xml)).  The function to read a line from a buffered stream returns a line in the stream's buffer. So, `refill` uses this function, rather than `read-line`.  An implementation for `read-line` must copy a line from the stream buffer to a specified buffer — this is an unnecessary step for `refill`.

**Comment by SirWumpus** [comment]
Will not pursue.
