### ISSUE TITLE
Functionality on/off

### ISSUE THREAD

**Issue by wboeke** [SirWumpus/post4#3]
Hello,
In post4 one can enable/disable functionality by means of macro's. E.g. in config.h:
#define HAVE_MATH_H 1
This is tested in post4.c as follows:
#ifdef HAVE_MATH_H
However: this always evaluates to true, also if HAVE_MATH_H has value 0. So: test it with #if, or else: outcomment the macro in config.h

Another small issue: In  post4.p4 the word 'value' is implemented in a very complicated way. This can be done much shorter however:

variable #msg  0 #msg !
create values  ' @  , ' !  , ' +! ,
: value ( n 'name')
   create ,
   does>  values #msg @ cells + @ execute  0 #msg ! ;
: to  1 #msg ! ;
: +to  2 #msg ! ;

I got this code from github.com/pahihu/vfc.

Kind regards,
Wouter Boeke

**Comment by SirWumpus** [comment]
Note. Separate issues / questions should have separate tickets.

* Did you first try `./configure --help` to see the available compile time settings?  If so you can disable math support with:

        make distclean
        ./configure --disable-math
        make 

* `VALUE` and `2VALUE` were implemented in such a way to deal with how `TO` works with variable length number of cells (there is no frilly `2TO`.  I was also allowing for future possibility of larger "values" beyond 2 cells.  The code was a bit legacy from years ago and would be happy to consider something simpler provided it doesn't break anything.  I'll review the code and test suite to see.

**Comment by wboeke** [comment]
About that HAVE_MATH_H issue: indeed it was my own fault. I had to make some modifications in the code, because the compiler generated a lot of errors. Probably not all compilation environments are equal.

By the way: wouldn't it be a good idea to skip the complete configure episode? For me it is something from the past, and it generates big incomprehensable makefiles. Most of the time I don't use them, and make my own.

**Comment by SirWumpus** [comment]
> By the way: wouldn't it be a good idea to skip the complete configure episode?

No.  I write my own `Makefiles` for (almost) all my portable projects.  I only use `autoconf` (not `automake`) to avoid BSD (main dev. env.), Linux, and Cygwin differences (and no I would not use `cmake`) to configure the makefiles and the .h files.

**Comment by SirWumpus** [comment]
Having tested the above suggested simplified implementation of `VALUE` and `TO`, it fails to pass the test cases WRT `2VALUE` and `FVALUE`.
