### ISSUE TITLE
A problem with :noname

### ISSUE THREAD

**Issue by wboeke** [SirWumpus/post4#4]
Hereby a little problem with a program that most forth's don't have trouble with:
```
: compose ( xt1 xt2 -- xt3 )
  >r >r :noname
    r> compile,
    r> compile,
    postpone ;
;
: f1 5 + ;
: f2 20 - ;
10 ' f1 ' f2 compose execute .
```
The correct output is -5, but the post4 message is:

post4: before $0000000000000301 ds=1 rs=3, after $0000000000000201 ds=1 rs=2
-22 thrown while compiling ":NONAME"

I "solved" this by simply disabling the check, but there should be a better solution!

**Comment by wboeke** [comment]
The original code comes from Rosetta:  https://rosettacode.org/wiki/Function_composition#Forth
And it works, and it contains only standard forth words, and it is okay in all other good forth's: then why should it be forbidden?

**Comment by ruv** [comment]
This code is incorrect:
```
: foo ( x x -- xt )
  >R >R  \ ( R: x x )
  [:
    R> COMPILE,
    R> COMPILE,
    POSTPONE
  ;] ( D: xt ) ( R: x x )
;
```

Because it violates [3.2.3.3 Return stack](https://forth-standard.org/standard/usage#usage:returnstack):
> - All values placed on the return stack within a definition shall be removed before the definition is terminated or before [EXIT](https://forth-standard.org/standard/core/EXIT) is executed.

The quotation is also incorrect. Because this code is equivalent to the following:
```
: _(foo)
    R> COMPILE,
    R> COMPILE,
    POSTPONE
;
: foo ( x x -- xt )
  >R >R  \ ( R: x x )
  ['] _(foo)
  ( D: xt ) ( R: x x )
;
```
Obviously, `_(foo)` in incorrect too.

**Comment by SirWumpus** [comment]
> This code is incorrect:
> 
> ```
> : foo ( x x -- xt )
>   >R >R  \ ( R: x x )
>   [:
>     R> COMPILE,
>     R> COMPILE,
>     POSTPONE
>   ;] ( D: xt ) ( R: x x )
> ;
> ```

Yes.  [I realised that yesterday.](https://github.com/SirWumpus/post4/issues/4#issuecomment-2245476101)

**Comment by wboeke** [comment]
Take your time! It's a tricky issue.

**Comment by SirWumpus** [comment]
> Take your time! It might be a tricky issue. That compose word worked okay in isolation, but gave wrong results if inside a larger forth program.

If you read the [answer from @ruv](https://github.com/ForthHub/discussion/discussions/159) there are certain cases where you cannot use it.
