### ISSUE TITLE
Add word to search or find file in path-list.

### ISSUE THREAD

**Issue by SirWumpus** [SirWumpus/post4#42]
Add word to search a path list like `OPEN-FILE-PATH ( list l file f fam -- fd ior )`.  The intent is to build a word like `INCLUDE-FILE-PATH` (`FIND-INCLUDE` maybe) to find files from env. var. `POST4_PATH`.  Early version of `INCLUDED` / `INCLUDE` used to do this implicitly, but that was altered recently to handle nesting and conformance issues.

Also add character constants `PATH-SEP` and `DIR-SEP` for OS portability.

**Comment by ruv** [comment]
> Also add character constants `PATH-SEP` and `DIR-SEP` for OS portability.

Note that Windows accepts the forward slash «`/`» as a path component separator.  This allows us to use relatives paths that work the same on Windows and Linux.

**Comment by SirWumpus** [comment]
Sidebar: I heard that DOS 1.0 used `/` originally but for fear of copyright or look'n'feel reasons DOS 2 used `\` (grrr hair pulling padded wall madness) and then used `/` for switches (grr).  The fact they allow both `\` and `/` now is a saving grace.  Though because of `DRIVE:` notation path-lists had to use `;` instead of `:`.  Semicolon is actually a better list separator IMO, but alas most *nix shells use `;` as a statement separator.  Oh hum the hoops of portability makes me feel like an ageing show dog that still learns new tricks.

**Comment by SirWumpus** [comment]
Sidebar: I like [Cygwin](https://www.cygwin.com/) for *nix like world on Windows; the `C:` notation from CP/M and DOS is supported but deprecated I think in favour of `/cygdrive/c` (little long and not as much fun as maybe using `/cyggy/c`), but its practical.

**Comment by SirWumpus** [comment]
The code works, not sure I'm happy with the word names, but without alternative suggestions, closing for now.
