### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by wboeke** [SirWumpus/post4#46]
1. Variable p4_build_info is listed both in main.c and in post4.c. My gcc compiler (gcc, Linux) thus generates an error.
2. This statement:
`2 3 4 .s` 
has output:
`$0000000000000002 $0000000000000003 $0000000000000004
`
Why so unreadable?
3. The configure script is very extensive. Maybe a bit overdone?
4. In the examples directory, nowhere a floating point or a file-handling example is given. 

Apart from all this: post4 works well and is very robust!

**Comment by SirWumpus** [comment]
1. `p4_build_info` which gcc version and which Linux.  I had no complaints from NetBSD, Rocky Linux, Ubuntu Linux (well none that were errors in the CI runs), and Cygwin.  However, given I recently split out the `main.c` from `post4.c` (hmm did I remove `#ifdef TEST` yet in `post4.c`) I'll see about cleaning that up.

2. `.s` prints the stack from `top-n` to `top-0`, the values on the stack can be anything pretty much and I work with hex addresses allot, plus I want the output to have some consistent uniformity (not fond of variable length lines much) similar to a dump and given I use `.s` and `.rs` a lot during development I wanted something that made sense to me; maybe a throw back to `gdb x/32gx` or CP/M's `ddt` and hex dumps I used so often in the past.

3. The `./configure` script was built from the `libsnert` `./configure`, which when I wrote it I needed it to work on OpenBSD, some Linux (probably Centos), Cygwin (Windows), Solaris, and Minix, which all had varying support for POSIX, X/Open (now SUS), and C library functions.  These days at least the ISO C11 and C17 support is pretty consistent I suppose I could prune a little and make assumptions (which I hated doing back then cause it bit me in the arse more than once).  When ever something went wrong with a libsnert / milter / BarricadeMX build it usually was some assumption of standard functions and/or locations of headers and libraries.  I grabbed the parts I needed for Post4.

4. Hmm.  I see if I can come up with some float and file examples.  There is always the test units for float and file access words in `test/` that might serve.  But I haven't had a short concise and interesting examples in those areas yet.

> Apart from all this: post4 works well and is very robust!

Thank you.  Kind of you to say.  I've been trying to make it as robust as possible and more Forth 2019 conforming (with thanks to @ruv).

When built without debug (default) then there are fewer active stack checks. For example `ok .` when the stack is empty actually prints the stack sentinel value.  With `--enable-debug` there are some extra stack checks on some of the more common words `.` `drop` `dup` (maybe some others) that generate a stack exception immediately which is pretty handy debugging.

Another interesting thing to try is the tracing (output still might need some tweaks):
```
ok 1 trace !
ok 4 9 min
ok 0 trace !
```

I also recently (like two days ago) added last input line editing (no I don't plan on more history, just wanted small short and sweet) you might like, see README.

**Comment by SirWumpus** [comment]
I should add that Post4 should also build on MacOS now.

**Comment by wboeke** [comment]
Thanks for your fast reply!
One extra little point: Usually I use options -Wall -Werror in makefiles. For post4 I had to add also:
```
-Wno-unused-variable -Wno-unused-value -Wno-parentheses  \
  -Wno-sequence-point
```
Maybe harmless warnings?
