### ISSUE TITLE
Case dependency?

### ISSUE THREAD

**Issue by wboeke** [SirWumpus/post4#51]
This statement works correctly:
`0 [IF] 2 [ELSE] 3 [THEN] .`
The following statement leaves post4 in a strange state:
`1 [if] 2 . [else] 3 . [then] .`
I have more questions, but this one maybe is important.

**Comment by SirWumpus** [comment]
This indeed an issue in the Forth 200x draft 19-1 [reference implementation](https://forth-standard.org/standard/tools/BracketELSE).  @ruv proposed an improved version that I'll look to adapt.

**Comment by SirWumpus** [comment]
@ruv Do you need really word lists for `[IF]` `[ELSE]` `[THEN]`?

**Comment by ruv** [comment]
@SirWumpus writes:

> @ruv Do you need really word lists for `[IF]` `[ELSE]` `[THEN]`?

These words can be implemented without word lists, using case-insensitive comparison of strings.

In general, I need word lists for my module framework (under construction).

**Comment by SirWumpus** [comment]
> In general, I need word lists for my module framework (under construction).

I have word lists now.  Just to change the old version for your elegant one requires some shuffling.

Sidebar: It would seem having a `COMPARE-NOCASE` (or `COMPARE-CASELESS`) would be a good thing to have generally.

**Comment by SirWumpus** [comment]
Sidebar: @ruv
> In general, I need word lists for my module framework (under construction).

What is your "module framework"?

**Comment by ruv** [comment]
> What is your "module framework"?

A Forth module is a Forth program that can be reused **independently** of the context. Every Forth module has a globally unique name (URI). A Forth module uses **only** other modules (including default modules of standard words).  Everything the module needs, it imports explicitly (except default modules). The user of a module just imports it and uses its functionality.  

When a module is loaded from a file, a binary module instance (or a binary image) is created. A module instance is reused when it is imported during creation of an instance of another module.  But, in some cases, another instance of the imported module may be created automatically (this is the most difficult and most interesting part).

The module framework is an engine that provides all this functionality.

**Comment by SirWumpus** [comment]
@ruv For your framework to work correctly, it sounds like you would need "unlimited" word lists or at least a larger number the minimum 8.  Also sounds like something similar to `rebar3`, `npm`, `cargo`, `cpan` and other language package systems.

> A module instance is reused

Do you mean "replaced"?  What about versioning issues where some modules depend on different versions of another (see this alot in npm tree).

In Forth's case I'd expect a simple newer-always-trumps unless you have some module-version-lock.

**Comment by wboeke** [comment]
About that case-sensitive [IF]: if it is according to the standard, then leave it as it is. Maybe only a remark in the documentation.
By the way: recursive [IF] is not possible, same e.g. in Gforth.

**Comment by SirWumpus** [comment]
Well case-sensitive or case-insensitive `[IF]` is implementation defined; most systems ignore case and Post4 does too; I only use case to visually distinguish between standard and user words.

As for recursive `[IF]` I assume you actually mean nested `[IF]`, in which case from my understanding of the code and standard's intent it should be allowed.

**Comment by ruv** [comment]
>  it sounds like you would need "unlimited" word lists or at least a larger number the minimum 8.

Yes, sure. You need at least one word list per each module (recursively).

>  Also sounds like something similar to rebar3, npm, cargo, cpan and other language package systems.

Yes, but this is a different and independent problem. 

> > A module instance is reused
>
> Do you mean "replaced"?

No. I mean, that when A uses D, and B uses D, the same instance of D is used in an instance of A and in an instance of B.
In the same time, the different instances of the same module can be created in some cases.

> What about versioning issues where some modules depend on different versions of another (see this alot in npm tree).

Different versions of the module are different modules. They all can be used in parallel.

When a module instance is created, it is provided with instances of the required versions of the modules being used.

**Comment by SirWumpus** [comment]
Ok. Big question: why a Forth module system?  How is this better than a simple `INCLUDE` or `REQUIRE`?  Seems like lot of overheard and extra complexity; if you need it maybe Forth is not the language for the task?  Makes me think of the Locals vs Stack Juggling discussion on `comp.lang.forth`.

**Comment by ruv** [comment]
>  How is this better than a simple `INCLUDE` or `REQUIRE`?

These tools are too low level. There are no means to define a module.


> if you need it maybe Forth is not the language for the task?

1. The problem is not in the Forth language itself, but in a library-level tool.
2. There are languages that support modules and for which package managers are already created. But each language has its own downsides.
3. There are no languages that support such a module system that I need.  Some close options are [Overriding Dependencies](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html) in Rust and  [Overriding Components from a Used Package](https://www.w3.org/TR/xslt-30/#package-overriding-components) in XSLT.

**Comment by ruv** [comment]
@wboeke [wrote](https://github.com/SirWumpus/post4/issues/51#issue-2582529532):
> The following statement leaves post4 in a strange state:
> `1 [if] 2 . [else] 3 . [then] .`

An implementation that works: [bracket-if.fth](https://github.com/ForthHub/fep-recognizer/blob/master/implementation/lib/bracket-if.fth).

An example of conditional loading if the system does not support lowercase `[if]`:
```forth
:noname ( sd.filename sd.test -- ) ['] evaluate catch if 2drop 0 then if 2drop else included then ;
s" ./lib/bracket-if.fth" s" 0 0 [if] [else] drop -1 [then]" 4 pick execute drop
```

**Comment by SirWumpus** [comment]
Have modified `examples/conditional_source.p4` as a test, but not updated the test suite.  Will do at some future date.
