### ISSUE TITLE
Not null-teminated strings for `included` and `open-file`

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#56]
https://github.com/SirWumpus/post4/blob/75a26404bd67d386cebd8014d90f576cc915948e/src/post4.p4#L2871

So, if we pass a string that is not null-terminated to `included`, it will not find the file?

If `included` (or, better, `open-file`, etc) needs a null-terminated string, it should check that and make a temporary copy by itself.

**Comment by SirWumpus** [comment]
It actually does make the copy with a terminating NUL byte already.  If you follow the words it gets to
[_string0_store](https://github.com/SirWumpus/post4/blob/75a26404bd67d386cebd8014d90f576cc915948e/src/post4.p4#L16477) which handles the copy to a temp. buffer and NUL.

**Comment by ruv** [comment]
I mean, that the following test fails:
```forth
s" test.fth-" 1- included
```

When the following works:
```forth
s" test.fth" included
```
