### ISSUE TITLE
Redirected input should terminate on first uncaught exception.

### ISSUE THREAD

**Issue by SirWumpus** [SirWumpus/post4#59]
>> In production (if not testing), multi-line scripts should not be run in interactive mode (i.e., be passed as the user input device).
>
> I disagree. 

In interactive mode, when an error occurs, the Forth system eventually discards the parse area (the remaining part of the input buffer) and reads the new line from the input stream (that is the user input device).

So if a script file is used as the user input device (by redirection), and an error occurs in the middle of the script (for example, a word is not found, or `r/o open-file throw` and the file is absent),  then interpreting of the remaining part of the script will probably produce more errors.  This does not make any sense in production.

Just an illustration of what I mean:
```shell
post4 <<EOF
: foo
  -#123 .
;
foo
EOF
```
There is no point in continuing to interpret the input file after the first error.  Therefore, you probably will not pass a script to the Forth system stdin in a production environment.

This also means that from the user's perspective it is better if `post4 script.p4` is equivalent to `post4 -i script.p4` rather than `post4 < script.p4`.

_Originally posted by @ruv in https://github.com/ForthHub/discussion/discussions/185#discussioncomment-11169487_

**Comment by SirWumpus** [comment]
Using this input:
```
132 dup . cr quit cr 456 . cr
.( say something clever here )
```

So something like this for the four cases:
```
elf$ ./post4 ../test/data/quit0.p4 ; echo $?
132
ok
3
elf$ ./post4 <../test/data/quit0.p4 ; echo $?
132
3
elf$ ./post4 -i ../test/data/quit0.p4 ; echo $?
132
ok
3
elf$ ./post4 ; echo $?
ok include ../test/data/quit0.p4
132
ok
3
elf$
```

**Comment by ruv** [comment]
1. Should not it output "say something clever here" in the second case (when the input is redirected)?

2. What is your rationale to provide a nonzero exit status when the system terminates due to the end of the input?
If the end of input is unexpected, the error -39 "unexpected end of file" can be thrown.

3. Why are the following cases produce different exit status?
```bash
echo "1" | post4  ; echo $?
echo "1 quit" | post4  ; echo $?
```

**Comment by SirWumpus** [comment]
> 1. Should not it output "say something clever here" in the second case (when the input is redirected)?

No, based on other other [this portion of discussion](https://github.com/ForthHub/discussion/discussions/185#discussioncomment-11169746) and the following 3 comments.   Because redirected input is not interactive (isatty(STDIN_FILENO) is false), so it terminates on the first uncaught exception.

>     2. What is your rationale to provide a nonzero exit status when the system terminates due to the end of the input?
>        If the end of input is unexpected, the error -39 "unexpected end of file" can be thrown.

As I've mentioned before (somewhere, I'm losing track where all the conversation threads), if the batch job or session generates one or more uncaught exception anytime during the job/session, then on EOF the exit status would be 3.  Otherwise a BYE or BYE-STATUS could exit with an explicit status.

I would not consider this to be a case of unexpected EOF.  Unexpected EOF in my mind would be when you only read part of a UTF8 encoding or part of a BASE64 quantum or similar case were you expect more input to complete some sequence.  Maybe EOF in an unfinished word definition would count too.

>     3. Why are the following cases produce different exit status?
> 
> 
> ```shell
> echo "1" | post4  ; echo $?
> echo "1 quit" | post4  ; echo $?\
> ```

`QUIT` is considered an exception even though it can never be caught; it terminates processing unexpectedly (?).  And follows much of the same code path as `ABORT` et al.  However I did pose a question of you a few days back as to whether it should be treated this way with no answer. 

Interactive users are less interested in the exit status; but redirected / scripted QUIT, ABORT, and THROW are exceptional and IMO should be treated all the same.

**Comment by ruv** [comment]
>  if the batch job or session generates one or more uncaught exception anytime during the job/session, then on EOF the exit status would be 3.

Ah, I see. I didn't think `QUIT` was an exception, so I thought it was because of EOF.


> However I did pose a question of you a few days back as to whether it should be treated this way with no answer.

Do you mean [this one](https://github.com/SirWumpus/post4/issues/54#issuecomment-2456182300)?


> Interactive users are less interested in the exit status; 

Agreed.   Then, it is not necessary to count uncaught exceptions in interactive mode.


> but redirected / scripted QUIT, ABORT, and THROW are exceptional and IMO should be treated all the same.

Well, I [still think](https://github.com/ForthHub/discussion/discussions/185#discussioncomment-11170409) that redirected `stdin` can be treated as interactive, at least in some cases (it is useful for testing).

I agree that `QUIT` and `ABORT` can be considered to have the same level of severity. But other uncaught exceptions have a **higher severity level**, for my taste 🙃

**Comment by SirWumpus** [comment]
> > if the batch job or session generates one or more uncaught exception anytime during the job/session, then on EOF the exit status would be 3.
> 
> Ah, I see. I didn't think `QUIT` was an exception, so I thought it was because of EOF.

How would you describe it?  It has an Exception Code, its part of `ABORT` which also has an exception code, disrupts normal control flow.

> > However I did pose a question of you a few days back as to whether it should be treated this way with no answer.
> 
> Do you mean [this one](https://github.com/SirWumpus/post4/issues/54#issuecomment-2456182300)?

Yes.  Though the answer felt underwhelming. 

> > Interactive users are less interested in the exit status;
> 
> Agreed. Then, it is not necessary to count uncaught exceptions in interactive mode.

Well the code paths are pretty much 99.9% the same for interactive / redirected or scripted. The only behaviour differences are no prompt, no command line editing when redirected/scripted.


> > but redirected / scripted QUIT, ABORT, and THROW are exceptional and IMO should be treated all the same.
> 
> Well, I [still think](https://github.com/ForthHub/discussion/discussions/185#discussioncomment-11170409) that redirected `stdin` can be treated as interactive, at least in some cases (it is useful for testing).

Redirected stdin is not interactive, since input is not from a terminal, but a stream. 

> I agree that `QUIT` and `ABORT` can be considered to have the same level of severity. But other uncaught exceptions have a **higher [severity level](https://github.com/ForthHub/discussion/discussions/185#discussioncomment-11170089)**, for my taste 🙃

Like hot spices, strong mustards, chillies, something with kick?  Mmm.

While other exceptions may be viewed or treated with greater importance, technically they behave the same as `ABORT`, just the exception code changes (and text description).  Other than `QUIT`, I don't see any difference with exceptions.  If there are differences, they're not clearly documented or explained.  There are a who list of exceptions that seem redundant or unused (at least in Post4), but they all behave like `ABORT` internally.

**Comment by ruv** [comment]
> Redirected stdin is not interactive, since input is not from a terminal, but a stream.

By "interactive mode" I only [mean a reaction](https://github.com/ForthHub/discussion/discussions/185#discussioncomment-11170235) on an uncaught exception. Maybe this term is not quite appropriate.

Anyway, the word `ACCEPT`, which reads characters from the user input device, usually works when stdin is redirected.

For example:
```shell
echo "foobar" | gforth -e 'pad dup 80 accept swap type cr bye'
```
Output:
```
foobar
```

**Comment by ruv** [comment]
> > 1. Should not it output "say something clever here" in the second case (when the input is redirected)?
> 
> No, based on other other [this portion of discussion](https://github.com/ForthHub/discussion/discussions/185#discussioncomment-11169746) and the following 3 comments. Because redirected input is not interactive `(isatty(STDIN_FILENO)` is false), so it terminates on the first uncaught exception.

The following two commands shall produce the same output:

```shell
post4 <<EOF
pad dup 80 accept
foobar
type cr
EOF
```

```shell
post4 <<EOF
quit
pad dup 80 accept
foobar
type cr
EOF
```

If `accept` reads the redirected stdin, than `quit` shall read it too, regardless the mode.

**Comment by SirWumpus** [comment]
> If `accept` reads the redirected stdin, than `quit` shall read it too, regardless the mode.

I'm confused.  Is that a good thing or a bad thing?

**Comment by SirWumpus** [comment]
OK.  I think I've come see how `QUIT` is not an exception.  As you've explained before `QUIT` is the historical REPL.  It cannot be caught since it resets the exception stack (at least it should).  As such QUIT on its own should not cause exit 3 at the end of session.  However other exceptions might occur along with QUIT during a session and at exit they (the other exceptions) result in exit 3.

Does that make sense?  (Probably as much sense as my puppy stealing my socks.)

**Comment by ruv** [comment]
> > If `accept` reads the redirected stdin, than `quit` shall read it too, regardless the mode.
> 
> I'm confused. Is that a good thing or a bad thing?

That is a good thing.  Otherwise, that would be inconsistent.

-----

>  It cannot be caught since it resets the exception stack (at least it should). 

Not only for that.  Even if the exception stack is not touched, nothing can be caught because it never throws an exception.

-----

> However other exceptions might occur along with QUIT during a session and at exit they (the other exceptions) result in exit 3.
> Does that make sense? 

Yes, a nonzero exit status makes sense in these conditions. At least, it can be noticed by the caller script/program when stdin is redirected.


> (Probably as much sense as my puppy stealing my socks.)

😄

**Comment by ruv** [comment]
>  Because redirected input is not interactive (`isatty(STDIN_FILENO)` is false), so it terminates on the first uncaught exception.

**Redirected input can be interactive** (i.e., under user's interactive control). For example, the Forth system process runs under `ncat`, and the user is on the other side of the pipe or socket. So I dislike the idea of determining interactive mode with `isatty`.

Perhaps `isatty` can be used to determine available capabilities, but not the mode.

As an example, in mysql client a similar problem exists (i.e., whether to terminate after the first error on stdin or continue), and it provides a command line argument to enable batch mode.

One more argument: it's formally unclear why `throw` does not call `quit` when there no exception frame and the stdin is redirected.

**Comment by SirWumpus** [comment]
> > Because redirected input is not interactive (`isatty(STDIN_FILENO)` is false), so it terminates on the first uncaught exception.
> 
> **Redirected input can be interactive** (i.e., under user's interactive control). For example, the Forth system process runs under `ncat`, and the user is on the other side of the pipe or socket. So I dislike the idea of determining interactive mode with `isatty`.
> 

Ah. Finally get what you mean by "Redirected input can be interactive", like telnet to a sock-et (beware of puppy) talking to Forth.

> Perhaps `isatty` can be used to determine available capabilities, but not the mode.

Well `isatty` means terminal, which means I can enable line editing & history, though I suppose that could allowed to pass through a socket.

> As an example, in mysql client a similar problem exists (i.e., whether to terminate after the first error on stdin or continue), and it provides a command line argument to enable batch mode.

I'll have to think about this, whether to add a new option.  Normally if I'm redirecting input I want it scripted or piped etc. by default because i'm writing some filter / command line script (like sed or awk) to process input.

> One more argument: it's formally unclear why `throw` does not call `quit` when there no exception frame and the stdin is redirected.

Huh?  I assume you are talking about the standard or you making a comment on Post4?

**Comment by ruv** [comment]
> > One more argument: it's formally unclear why `throw` does not call `quit` when there no exception frame and the stdin is redirected.
> 
> Huh? I assume you are talking about the standard or you making a comment on Post4?

When `post4` terminates on the first uncaught exception if _the input is redirected_, it violates the behavior specified by the standard.  But it's unclear **what the formal difference** is between "_redirected input_" and "_not-redirected input_".

An argument in the command line (that enables terminating on the first uncaught exception) is a clear and obvious thing, at least. And it can be considered as a system-dependent program.

**Comment by SirWumpus** [comment]
> When `post4` terminates on the first uncaught exception if _the input is redirected_, it violates
> behavior specified by the standard. But it's unclear **what the formal difference** is between "_redirected input_" and "_not-redirected input_".

Well originally I didn't terminate on first uncaught exception.  But then you gave me feed back about how continuing to process would yield useless knock-on exceptions when input is redirected.

Now you don't like this idea of terminating on first uncaught exception for redirected input.

Which is it?  I can remove the `is_tty` check I added and restore the old behaviour, which wouldn't be bad IMO (the is_tty check feels like a hack).  The user just has to understand the first error is the only one that matters.  Its much like early C compilers would generate a cascade of knock-on errors; fix the first and a whole bunch of errors go away.

In many ways I prefer this old behaviour, because the program behaves consistently for interactive  and redirected input.

**Comment by ruv** [comment]
>  But then you gave me feed back about how continuing to process would yield useless knock-on exceptions when input is redirected.

Yes, but that was an argument for adding a command line option that enables batch mode 🙃 

`is_tty` can be useful to enable line editing (if not in batch mode).

> The user just has to understand the first error is the only one that matters.

If the user redirects a file to stdin, he should probably enable batch mode (to terminate on the first error). If the user redirects _user input_ from another program/pipe to stdin, they will not enable batch mode.
