### ISSUE TITLE
Negative depth when stack is dumped

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#61]
`.s` should not dump stack when depth is less then 0 (i.e., the stack is underflow).

Currently, `. .s` on empty stack prints many zeros.

https://github.com/SirWumpus/post4/blob/5a04efa4cc119e74ff05eadff9ca5a67fa29f241/src/post4.c#L2065-L2069
Perhaps `( addr u -- )` should be changed to `( addr n -- )`, and if _n_ negative then nothing is dumped, and the exception -4 can be thrown if desired.

**Comment by SirWumpus** [comment]
Not sure how or what you are seeing, but I currently see this.
```
elf$ ./post4
ok . .s

>> . .s
>>  ^
-4 thrown: stack underflow
ok
```

**Comment by SirWumpus** [comment]
I cannot duplicate the issue, but have placed an upper bound on `p4StackDump()` in case a stack becomes corrupted and tries to print bogus data.

**Comment by ruv** [comment]
```output
...
top-4294933674 $0000000000000000 $0000000000000000 $0000000000000000 $0000000000000000
top-4294933670 $0000000000000000 $0000000000000000 $0000000000000000 $0000000000000000
top-4294933666 $0000000000000000 $0000000000000000 -9 thrown: invalid memory address

>>
>> ^
-9 thrown: invalid memory address
ok
```

When depth is -1, `_ds` returns -1 in the second position:
https://github.com/SirWumpus/post4/blob/5a04efa4cc119e74ff05eadff9ca5a67fa29f241/src/post4.c#L2047-L2052

which interprets as unsigned number in `p4StackDump`:
https://github.com/SirWumpus/post4/blob/5a04efa4cc119e74ff05eadff9ca5a67fa29f241/src/post4.c#L380-L381

**Comment by SirWumpus** [comment]
But the stack depth returned from `_ds` should never be negative unless it was some how "stepped".

**Comment by ruv** [comment]
>  have placed an upper bound on p4StackDump() in case a stack becomes corrupted and tries to print bogus data.

`P4_LENGTH` returns a signed number (namely, [ptrdiff_t](https://en.cppreference.com/w/cpp/types/ptrdiff_t) that is signed). Then this number is passed to `p4StackDump`.  Thus, `p4StackDump` must interpret it as signed and check not only for too large value, **but also for a negative value**.

For example, this value is negative when you do `drop` on the empty stack.

`drop _ds . . . ` outputs: `64 -1 140736755143952 ok`

**Comment by SirWumpus** [comment]
```
# define P4_LENGTH(stack)		((ptrdiff_t)((stack).top + 1 - (stack).base))
```
When stack is empty "top+1 = base".  In order to get P4_LENGTH equal -1, top would have had to underflow by one earlier.  

I think I might have to leave more stack checks enabled when --disable-debug (default) is used.  I typically have --enable-debug, which turns on some extra checks to avoid under/over flows.

**Comment by ruv** [comment]
It's not critical.  It was just a typo, but it was unexpected that `.s` will dump all available memory if the stack is underflow.

**Comment by SirWumpus** [comment]
Well I have been consider making some of my debug code "always on" to provide a more stable environment that would be well suited for developers coming from other languages.  Catching stack under/over flows sooner is usually best IMO.

Sideways: BTW have you played with `TRACE` at all?  Think the output needs some tweaking (you might have noticed the `_pp!` in `post4.p4` which is in aid of `TRACE` (though I had other plans for `poppush` counts for stack checking).

**Comment by SirWumpus** [comment]
> It's not critical. It was just a typo, but it was unexpected that `.s` will dump all available memory if the stack is underflow.

Ya. I've had similar experience too in other parts.  Usually sends me on wild goose chase for better part of a day.

**Comment by ruv** [comment]
>  Catching stack under/over flows sooner is usually best IMO.

I see a problem not in that, but in **data type mismatching**.

`_ds` returns `( -- aaddr n s )`, more accurately: `( -- a-addr n.depth u.size )`, where _n.depth_ is **signed**,
and this _n.depth_ is passed into _length_ of `p4StackDump(FILE *fp, P4_Cell *base, unsigned length)`, where _length_ is **unsigned**:
https://github.com/SirWumpus/post4/blob/5b85ce703a133803b03a3a8dc69b7891a58e4749/src/post4.c#L381

Either `_ds` shall return unsigned depth (i.e., 0 if the depth is negative),  or  `p4StackDump` shall accept signed "length".

**Comment by SirWumpus** [comment]
> Either `_ds` shall return unsigned depth (i.e., 0 if the depth is negative), or `p4StackDump` shall accept signed "length".

Leaving n.depth as-is and having p4StackDump() passed signed int probably better, especially for detecting error conditions.

**Comment by ruv** [comment]
> Sideways: BTW have you played with `TRACE` at all? Think the output needs some tweaking

No, I have not played with `TRACE` earlier.    I'm just testing it now.

When a number on a stack is a constant, you might want to show this constant name instead of (or along with) the number.

**Comment by SirWumpus** [comment]
```
elf$ ./post4
ok : x true ;
ok 1 trace !
ds=0  fs=0  rs=1  _inter_loop
ok x
ds=0  fs=0  rs=1  x
ds=0  fs=0  rs=2    TRUE
ds=1  fs=0  rs=3      @         $72439adcf118 ; - ; -
ds=1  fs=0  rs=3      _;
ds=1  fs=0  rs=2    _;
ds=1  fs=0  rs=1  _inter_loop
ok
```
Constants in word definitions appear by name obviously as they're compiled in.  Tying the constant once on the stack to its name, might be impossible without a specialised stack.  While very cool and would be a nice teaching/debugging tool, not sure its practical beyond that.
