### ISSUE TITLE
Invalid memory address under rlwrap

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#63]
When post4 is run under [rlwrap](https://github.com/hanslub42/rlwrap) (a readline wrapper), it shows error -9 on every input line.
```shell
rlwrap post4
```
Output:
```output
ok -9 thrown: invalid memory address
```

Ctrl+D doesn't help, Ctrl+C doesn't either.  Only `kill -9`.

Probably, it's a bug in post4.

**Comment by SirWumpus** [comment]
I've never used `rlwrap`.  I did implement my own light weight [line/history editing](https://github.com/SirWumpus/post4#tty-line-editing) `aline.c` that is NOT GPL like `readline`.  I might separate `aline` into its own library repository for 3rd party programs.

So `rlwrap` might be butting heads with `aline`'s own `termios` management, which ensures `ISIG` is enable to maintain most special signals.  However, I'll see if I can see if I can make it work with `rlwrap`, but suspect the two will be incompatible.

**Comment by SirWumpus** [comment]
rlwrap has lot of over head for line editing vs aline's ~8K of code, ~1,5K compiled 😎

```
elf# pkgin requires rlwrap
Shared libraries required by rlwrap-0.46.1:
        /usr/pkg/lib/libreadline.so.8
        /usr/lib/libutil.so.7
        /usr/lib/libterminfo.so.2
        /usr/lib/libcurses.so.9
        /usr/lib/libc.so.12
```

**Comment by SirWumpus** [comment]
If you've downloaded recent commits, in particular a31908772f, then you can build:
```
cd post4/src
make DBG='-DALINE_BASIC_INPUT' clean build
rlwrap -A -b'' ./post4
```
Should behave as expected.  

When built with `-UALINE_BASIC_INPUT` (default) not sure the what causes the -9 SIGSEGV just yet.  It could be that Aline issues the ANSI report ESC sequence to query the current ANSI cursor position.  Not sure rlwrap likes that.

**Comment by SirWumpus** [comment]
I have been able to duplicate the error case (I think).
```
elf$ rlwrap  -A ./post4
ok foo

rlwrap: warning: rlwrap appears to do nothing for post4, which asks for
single keypresses all the time. Don't you need --always-readline
and possibly --no-children? (cf. the rlwrap manpage)

warnings can be silenced by the --no-warnings (-n) option


>> foo
>>   ^
-13 thrown: undefined word
ok

elf$ rlwrap  --always-readline -A ./post4
ok foo
-9 thrown: invalid memory address
ok
```

**Comment by SirWumpus** [comment]
I believe I've fixed the SIGSEGV.  However, using `rlwrap` with Post4's own `Aline` editing appears to make a mess of the screen and is unusable since Aline sends ANSI ESC sequences to perform line edits and position the cursor, while `rlwrap` attempts to do similar using Curses library.

If I could detect `rlwrap` I could disable the line editing support, but `stdin` still appears as a terminal to Post4, since `rlwrap` setups a pseudo-tty and it sets no environment variable during the session.

I'm not going to pursue this further.

**Comment by ruv** [comment]
> I believe I've fixed the SIGSEGV. 

Yes, it is not reproducible on my side either.

> However, using rlwrap with Post4's own Aline editing appears to make a mess of the screen and is unusable since Aline sends ANSI ESC sequences to perform line edits and position the cursor, while rlwrap attempts to do similar using Curses library.

Got it. That's acceptable. The problem was only in SIGSEGV. I was using `rlwrap` before `Aline` was included into Post4, and noticed this SIGSEGV with a new version of Post4.

I wonder why Ctrl+D does not end Post4 under `rlwrap`.

**Comment by SirWumpus** [comment]
CTRL+D works for me as does CTRL+C (INT) and CTRL+\\ (QUIT). 

I do notice with rlwrap lots of flicker as it redraws constantly, that might be have been influenced by Aline.  Again its possible to disable Aline at compile time with 

        make DBG='-DALINE_BASIC_INPUT' clean build

which just uses the system's canonical line input, in which case I think there is less flicker.  If I could detect rlwrap during runtime, I could disable the built-in line editing & history on the fly, but so far I see nothing that helps.

**Comment by SirWumpus** [comment]
I have considered an option for this, but don't like the idea much.

How many OTHER programs like `rlwrap` are there doing the same thing?  I know of libraries like readline and libedit, but not other programs like rlwrap.
