### ISSUE TITLE
`order` shall not display contents

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#67]
The word [16.6.2.1985 `ORDER`](https://forth-standard.org/standard/search/ORDER) shall not display definition names from word lists, but only labels/identifiers for word lists:
  - > Display the word lists in the search order
  
The word [15.6.1.2465 `WORDS`](https://forth-standard.org/standard/tools/WORDS) displays words and it is specified as:
  - > List the definition names 

It is very inconvenient that you can't see the search order with `order`, instead the whole screen is filled with the names of words from these word lists.

**Comment by SirWumpus** [comment]
Guess I misread the definition of `ORDER` "display the word lists [and their contents]".  Oops.

**Comment by SirWumpus** [comment]
Something like...
```
elf$ ./post4
ok wordlist constant w
ok order
Search: 1  Define: 1
ok 1 w 2 set-order
ok order
Search: 2  1  Define: 1
ok
```

**Comment by ruv** [comment]
Some examples of what `orders` outputs in different Forth systems:

In Gforth:
```output
variant.gamma scratchpad Forth Forth Root     variant.gamma
```

In VfxForth:
```output
5298736  5284760  FORTH  EXTERNALS  ROOT
Current: 5298736
```

In SP-Forth:
```output
Context: <NONAME>:5731668  <NONAME>:5729784  FORTH
Current: <NONAME>:5731668
```

**Comment by SirWumpus** [comment]
I don't have any reverse mapping of `wid` to a name.  Its literally an index.
