### ISSUE TITLE
Incorrect (false positive) floating point recognizing

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#68]
**Any** lexeme that starts with `e` (or with a regexp `\d*e`) is recognized as a floating point number. Thus, any missed word that starts with `e` does not cause an error (as expected), but is unexpectedly translated as `0e`.

A testcase of the expected behavior:
```forth
t{ s" 0 0 efoobar-undefined-word" ' evaluate catch nip nip -> 13 }t
```

**Comment by ruv** [comment]
`1efoobar-undefined-word` is still incorrectly recognized as a floating point number.

See the format in [12.3.7 Text interpreter input number conversion](https://forth-standard.org/standard/float#float:conv).

**Comment by SirWumpus** [comment]
I really shouldn't fix bugs before bed.
