### ISSUE TITLE
Incorrect result when entering some double-cell integers

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#70]
Testing the recent changes to double-cell integers input notation support ([1](https://github.com/SirWumpus/post4/commit/111fc85cca13287c30863515a068eaadf492641d), [2](https://github.com/SirWumpus/post4/commit/0ec6c3f1d95fcc90fd0092fcc930f76ff32346c8)).

- `-1 0  1. d+  d.`
  - prints: `18446744073709551616`
- `18446744073709551616. d.`
  - prints: `0`  (very unexpected)

If this case is not supported, it might be better to throw an exception.  On the other hand, this means detecting a single-cell integer overflow, which can be overly burdensome.

**Comment by SirWumpus** [comment]
Do you try the update I pushed about 38 minutes ago?

**Comment by SirWumpus** [comment]
```
elf$ ./post4
ok -1 -1 1. d+ d.
0 ok -1. 1 0 d+ d.
0 ok
```

**Comment by ruv** [comment]
> Do you try the update I pushed about 38 minutes ago?

I tested the commit [#111fc85](https://github.com/SirWumpus/post4/commit/111fc85cca13287c30863515a068eaadf492641d), and now tested [#0ec6c3f](https://github.com/SirWumpus/post4/commit/0ec6c3f1d95fcc90fd0092fcc930f76ff32346c8) — the result is the same.

`18446744073709551616. d.` prints `0`, but this number is in the range of double-cell integers (128 bits).

**Comment by SirWumpus** [comment]
Hmm.  I didn't anticipate very large 128 number being entered in this way; Forth draft 19-1 section "8.3.1 Text interpreter input number conversion" gives the impression it was intended for converting single cell to double cell.  Now I have to think how best to handle 128 bit input (serves me right for thinking I was doing a useful thing, but failed to see all the implications; oh whip me with a wet noodle, grr).

**Comment by ruv** [comment]
>  I didn't anticipate very large 128 number being entered in this way; 

Yes, such numbers rarely used in source codes, but interactively, when testing something — it is quite possible.

>  gives the impression it was intended for converting single cell to double cell

Agreed, [that](https://forth-standard.org/standard/double#subsection.8.3.1) is not quite clear:
  - > When the text interpreter processes a number, except a `<cnum>`, that is immediately followed by a decimal point and is not found as a definition name, the text interpreter shall convert it to a double-cell number.
 
 "**it**" refers to the **numeric literal**, not to a binary number on the stack. The first occurrence of "a number" should be replaced by "a numeric literal" or by "a lexeme".

Also, it implies the word [6.1.0570 `>NUMBER`](https://forth-standard.org/standard/core/toNUMBER) can be used. BTW, `>number` in Post4 handles this case correctly:

```forth
t{  -1 0  1. d+ 2dup <# #s #> 0. 2swap >number 2drop d= -> true }t
```

**Comment by SirWumpus** [comment]
> > I didn't anticipate very large 128 number being entered in this way;
> 
> Yes, such numbers rarely used in source codes, but interactively, when testing something — it is quite possible.
>

\<Charlie Brown>Good grief!\</> 🤦‍♂️

> > gives the impression it was intended for converting single cell to double cell
> 
> Agreed, [that](https://forth-standard.org/standard/double#subsection.8.3.1) is not quite clear:
> 
>     * > When the text interpreter processes a number, except a `<cnum>`, that is immediately followed by a decimal point and is not found as a definition name, the text interpreter shall convert it to a double-cell number.

The example given could be more comprehensive too:
```
For example, entering DECIMAL 1234 leaves the single-cell number 1234 on the stack, and entering
DECIMAL 1234. leaves the double-cell number 1234 0 on the stack
```
Since it only shows the single to double cell case.

> "**it**" refers to the **numeric literal**, not to a binary number on the stack. The first occurrence of "a number" should be replaced with "a numeric literal" or "a lexeme".
> 
> Also, it implies the word [6.1.0570 `>NUMBER`](https://forth-standard.org/standard/core/toNUMBER) can be used. BTW, `>number` in Post4 handles this case correctly:

Think I had help with `>NUMBER`, but pleased I got something right 😉

> ```forth
> t{  -1 0  1. d+ 2dup <# #s #> 0. 2swap >number 2drop d= -> true }t
> ```

Will add.
