### ISSUE TITLE
Java build sef.faults when POST4_PATH is undefined.

### ISSUE THREAD

**Issue by SirWumpus** [SirWumpus/post4#71]
If I the `POST4_PATH` environment variable is not set for `post4.jni.Post4`, SIGSEGV occurs.

This fails:
```shell
java -Djava.library.path="" -cp ../.. post4.jni.Post4
```

This succeeds:
```
POST4_PATH=".:../src:../examples" java -Djava.library.path="" -cp ../.. post4.jni.Post4
```

_Originally posted by @ruv in https://github.com/SirWumpus/post4/issues/64#issuecomment-2469007685_

**Comment by SirWumpus** [comment]
Very odd given that [post4.c handles this](https://github.com/SirWumpus/post4/blob/cfdfa6417ed58a296fc620462e9e1572789ebc57/src/post4.c#L2521-L2523).

**Comment by SirWumpus** [comment]
Appears to work for me:
```
elf$ pwd
/home/achowe/git/com/snert/src/post4/jni
elf$ echo $POST4_PATH

elf$ java -Djava.library.path="" -cp ../.. post4.jni.Post4
CAFEBABE Monaco 377 e 2.718280 PI 3.141590 Planck's 6.626070E-34
ok
```

**Comment by ruv** [comment]
> Very odd given that [post4.c handles this](https://github.com/SirWumpus/post4/blob/cfdfa6417ed58a296fc620462e9e1572789ebc57/src/post4.c#L2521-L2523).

Probably, the build in value `P4_CORE_PATH` is correct in your case, and incorrect in my case.

If we do not provide a correct path to "src", it fails with SIGSEGV:
```shell
POST4_PATH="." java -Djava.library.path="" -cp ../.. post4.jni.Post4
```
