### ISSUE TITLE
Add `SYNONYM`.

### ISSUE THREAD

**Issue by SirWumpus** [SirWumpus/post4#75]
>The word `synonym` is wanted (see also the proposal [Tighten the specification of `SYNONYM`](https://forth-standard.org/proposals/tighten-the-specification-of-synonym-version-1-?hideDiff#reply-1107)).

_Originally posted by @ruv in https://github.com/SirWumpus/post4/discussions/74#discussioncomment-11302541_

**Comment by SirWumpus** [comment]
@ruv Should `SYNONYM` maintained flags / behaviour of words defined as `IMMEDIATE` (`compile-only` too)?  I can see arguments both ways.  I prefer that `IMMEDIATE` not be retained and leave it to the developer to re-apply it ***IF*** they require it to the new name, eg. `SYNONYM [CHAR] CHAR IMMEDIATE` or `SYNONYM CH [CHAR]` would strip it.

**Comment by SirWumpus** [comment]
> BTW, I need a mean to create a named definition for an xt that takes both the xt and name (a string) from the stack, and the execution token for the created definition is the same xt.

Huh?  Come again?  What pray tell are you on about?

BTW Post4 is a system where `xt = nt`.  I did start to read [The new GForth Header](http://www.euroforth.org/ef19/papers/paysan.pdf paper but was interrupted and put on back-burner then in a folder called `Ertl` for rainy day.

**Comment by ruv** [comment]
😄

I mean, the word `alias` takes a name from the input buffer. But for a programming tool it's more convenient to take arguments from the stack. And binding an xt to a name in the compilation word list is a very basic programming-tool factor.

`xt = nt` is quite standard-compliant. 

Gforth has complex headers with associated virtual method tables. I would not consider them as an example to follow for a simple Forth system 🙃

**Comment by SirWumpus** [comment]
> Gforth has complex headers with associated virtual method tables. I would not consider them as an example to follow for a simple Forth system 🙃

I don't plan on following GForth.  I am just interested in some topical papers.  Always good to know where not to go.  I like that Post4 appears to be simple (to me and I hope others), largely complete, and hopefully 2019 compliant system.  Its not glossy, not too big, and certainly NOT GNU (these days GNU tagged software starts to leave bad taste in my mouth).  

Hmm. `GNU = GNU Not Unix` so `NOT GNU` is a unix?
