### ISSUE TITLE
`catch` is inconsistent on stack underflow

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#79]
Why is the result from `catch` different from case to case when the stack is underflow?
Below is a transcript.
```transcript
╰─>$ post4
ok ' drop catch .

>> ' drop catch .
>>             ^
-4 thrown: stack underflow
input: ' drop catch .ok
ok
ok .
-9 ok
ok ' drop catch .

>> ' drop catch .
>>             ^
-9 ok
ok
```

Note that no number is printed after `catch` in the first case.

**Comment by SirWumpus** [comment]
Well I can duplicate this (unfortunately).  A quick `gdb` looks like some issue with the longjmp.  Will look further.

**Comment by ruv** [comment]
> Note that no number is printed after `catch` in the first case.

Formally, this is allowed if `catch` returns 0, and the Forth text interpreter detects stack underflow after interpreting `catch`, and throws an exception.  But in such a case the stack shall be empty after printing an error message.

This code:
```forth
:noname ['] drop catch . ; execute
``` 
shall print only an exception number.

```transcript
╰─>$ post4
ok :noname ['] drop catch . ; execute

>> :noname ['] drop catch . ; execute
>>                                  ^
-4 thrown: stack underflow
input: :noname ['] drop catch . ; execute-9 ok
```
It prints some text and then `-9` at the end (before "ok").

**Comment by ruv** [comment]
I'm just wondering:
with the empty stack, `' drop catch` still prints:
```output
>> ' drop catch
>>            ^
```
But it does not print that on other errors. Then why does it print that for `-4` error?

Also, some problem still exists. A transcript:
```transcript
╰─>$ post4
ok 0 ' @ catch .
ok depth .
2 ok .s
ds
top-01 $0000000000000000 $fffffffffffffff7
ok . .
-9 0 ok
ok ' drop catch .

>> ' drop catch .
>>             ^
-9 ok
```
Note that the number `-9` is not printed after the first `catch`.  And on the next `catch` the throw code is inappropriate.

**Comment by SirWumpus** [comment]
Are you using commit edbdbef2bc?

First case doesn't print anything.  Second case does print (`.` in the input buffer).
```
elf$ ./post4
ok ' drop catch

>> ' drop catch
>>            ^
ok .
-4 ok ' drop catch .

>> ' drop catch .
>>             ^
-4 ok
```
That case appears to work correctly.

```
ok 1 ' @ catch .
ok .
-9 ok 1 ' @ catch .
ok .
-9 ok 1 ' @ catch
ok 1 ' @ catch
ok .
-9 ok
```
I actually tried that one before you retested and noticed that the output after `CATCH` doesn't happen.  Not sure yet as to why; current guess is that the input is unintentionally reset (maybe related to the difference in signal handling vs thrown cases).

SideSalad: I notice in the Forth 19-1 draft that 9.6.1.0875 `CATCH` makes no mention of saving the input source, while 9.6.1.2275 `THROW` does.  I know my implementation, based on the reference one, does not save nor restore input source and it seems confusing as to what is expected.  Frankly CATCH and THROW should NOT play with input; that should be left to other words (otherwise you could be wasting stack space with redundant frames).

**Comment by ruv** [comment]
> Are you using commit https://github.com/SirWumpus/post4/commit/edbdbef2bc2d5b1dff0c98038bb23d97ff43691d?

Yes, sure!

> First case doesn't print anything.

It prints:
```output
>> ' drop catch
>>            ^
```
in your transcript too 🙃

**Comment by SirWumpus** [comment]
Well that is intentional for [some exceptions](https://github.com/SirWumpus/post4/blob/edbdbef2bc2d5b1dff0c98038bb23d97ff43691d/src/post4.c#L1352-L1356), like [stack underflow](https://github.com/SirWumpus/post4/blob/edbdbef2bc2d5b1dff0c98038bb23d97ff43691d/src/post4.c#L1047-L1048) since its not `ABORT` or `ABORT?`

**Comment by SirWumpus** [comment]
My concern was the (lack of) output when SIGSEGV is caught vs something like stack underflow.

**Comment by ruv** [comment]
> My concern was the (lack of) output when SIGSEGV is caught vs something like stack underflow.

I see now. That's OK.   In such cases, the return stack trace is more useful than the input buffer (both can be printed).

-----

> SideSalad: I notice in the Forth 19-1 draft that 9.6.1.0875 `CATCH` makes no mention of saving the input source, while 9.6.1.2275 `THROW` does.

Yes, I didn't notice it right away either (see my [comment at forth-standard](https://forth-standard.org/standard/exception/THROW#reply-991)).  

`THROW` _formally_ restores what `INCLUDE-FILE` saves, because `INCLUDE-FILE` does not _formally_ receive control back from the interpreter in a case of an exception.

> Frankly `CATCH` and `THROW` should NOT play with input; that should be left to other words

Yes. And `CATCH` does not play with the input.

Is was _formally_ specified in this way (i.e., that `THROW` restores input) because the Exception word set was optional.

**Comment by SirWumpus** [comment]
My head hurts, actual head ache, not bug report induced, so I might be a little off in reasoning:  I see an imbalance with `THROW` if `CATCH` doesn't save input source, let alone knowing that there is a input source frame on "a" stack some place placed there by some word like `INCLUDE-FILE`.  Think its better `THROW` not play with input source.

Post4 will `...CATCH _input_pop THROW...` to make sure input source save/restore remains balanced.  I assume other implementation do something similar.

(Sorry if my reasoning is off or unclear, head throbbing, and not from any virtual brick wall.)

**Comment by SirWumpus** [comment]
I think I've sorted the output inconsistency.  Made some changes and now the output looks more uniform for signals and exceptions.
```
elf$ ./post4
ok ' drop catch .
-4 ok drop

>> drop
>>    ^
-4 thrown: stack underflow
input: drop
$000000000060c1e0  _interpret
ok 1 ' @ catch .
-9 ok 1 @

>> 1 @
>>   ^
-9 thrown: invalid memory address
input: 1 @
$000000000060c1e0  _interpret
ok
```
Want to see if I can get some test cases for this before I push the fix.

**Comment by SirWumpus** [comment]
Also have to pick an output format (currently have two versions for the input).

**Comment by ruv** [comment]
A return stack trace (traceback) makes sense if it starts from the initial point of the exception. There is no point in showing a traceback only from the point of the last re-throw.

So, if you want to show a traceback, there are two approaches:
  - save the traceback in the point of initial exception, and then show it when [the system's handler](https://github.com/SirWumpus/post4/blob/edbdbef2bc2d5b1dff0c98038bb23d97ff43691d/src/post4.c#L1350) gets control (if any).
  - show (perhaps in stderr) the traceback right at the point of initial exception only.

You can save/show a return stack trace for exceptions like SIGSEGV only, or for all exceptions (if configured for debugging).

There are a number of difficulties with any approach. For example, what to do on a re-throw, what to do on a side throw, how long to keep a saved backtrace, etc.

As an example, SP-Forth/4 shows a stack trace only for [hardware exceptions](https://en.wikipedia.org/wiki/Exception_handling#Hardware_exceptions), once they occur (i.e., in the initial point).  `INCLUDE-FILE` saves the input source position (file name, line number, input buffer, position) on any exception, but only if the previous position has been already shown. Otherwise it does not save the position. The system's handler (when it gets control) shows the saved position and sets a flag that the position was shown.


PS hope your headache is gone 🤗

**Comment by SirWumpus** [comment]
Well, for caught exceptions I do not want to show a stack trace, since they have been accounted for.

It is the uncaught exceptions and signals that can be handled cleanly (SIGSEGV is always messy).  So in theory a stack trace should help track at what point during runtime an exception occurs.

**Comment by ruv** [comment]
```transcript
╰─>$ post4
ok ' drop catch . cr
-4
ok 0 ' @  catch . drop cr
-9
ok ' drop catch . cr
-9
ok
```

Why does `catch` return `-9` instead of `-4` in the last case?

**Comment by SirWumpus** [comment]
https://github.com/user-attachments/assets/84a47ddd-fe51-4298-907f-14b112db4df9

**Comment by ruv** [comment]
Sorry, but the [problem](https://github.com/SirWumpus/post4/issues/79#issuecomment-2506631144) still exists.

**Comment by SirWumpus** [comment]
> Sorry, but the [problem](https://github.com/SirWumpus/post4/issues/79#issuecomment-2506631144) still exists.

It works fine for me since the last fix.

```
elf$ ./post4
ok ' drop catch . cr
-4
ok 0 ' @  catch . drop cr
-9
ok ' drop catch . cr
-4
ok
```

**Comment by ruv** [comment]
Hmm... interesting.  I checked in Cygwin, the result is the same on my side:
```transcript
$ ./post4.exe
ok ' drop catch . cr
-4
ok 0 ' @ catch nip . cr
-9
ok ' drop catch . cr
-9
ok
ok ' abort catch . cr
-1
ok ' drop catch . cr
-28
ok
```

```transcript
$ ./post4.exe -V | grep COMMIT
COMMIT="v0.13.0-22-g8952943"
```

**Comment by SirWumpus** [comment]
Ok.  I can duplicate that on Cygwin too.

**Comment by SirWumpus** [comment]
How(e) about now?

**Comment by SirWumpus** [comment]
> Now that is fixed! As I see it was a very subtle bug due to a function parameter being restored in a register during `longjmp` 🔥

Yep.  Subtle and annoying that the same compiler does not build the same way across OSes with the same CPU.  Different CPU, sure I can understand, but NetBSD vs Linux on x86_64 - nope.  Just not in the tarot cards, tea leaves, chicken entrails, guano droppings, and assorted other mystical divining methods.

Just goes to show, you really need at least three different build platforms just be sure and beware of Minority Reports.
