### ISSUE TITLE
The word `key?` shall not wait for input

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#80]
Currently, the word `key?` waits for input if a character is not available. But it shall immediately return false in this case.

[10.6.1.1755 `KEY?`](https://forth-standard.org/standard/facility/KEYq) says:
- > If a character is available, return _true_. Otherwise, return _false_.

**Comment by SirWumpus** [comment]
The code for `KEY?` set [non-blocking input](https://github.com/SirWumpus/post4/blob/edbdbef2bc2d5b1dff0c98038bb23d97ff43691d/src/post4.c#L2063-L2066).  It should not be waiting for input.

@ruv how did you test this?

**Comment by ruv** [comment]
The following command prints `0` as expected:
```shell
echo 'key? . cr ' | post4
```

But when interactive, it always waits for input if a character keyboard event is not available:
```transcript
╰─>$ post4
ok key? dup . [if] key . [then]
-1 10 ok
ok key? dup . [if] key . [then]
-1 32 ok
ok key? dup . [if] key . [then]
-1 113 ok
ok key? dup . [if] key . [then]
-1 111 ok
ok
```
Interesting that `accept` does not receive the available character.

**Comment by SirWumpus** [comment]
Works for me:
```
elf$ ./post4
ok key? dup . [if] key . [then]
0 ok key? dup . [if] key . [then]
0 ok key? dup . [if] key . [then]
0 ok key? dup . [if] key . [then]
0 ok key? dup . [if] key . [then]
```

> echo 'key? . cr ' | post4

You testing against an older installed version?  Noticed you didn't say `./post4` just be clear.

**Comment by ruv** [comment]
> You testing against an older installed version? Noticed you didn't say `./post4` just be clear.

I have a `post4` "shim" in `/usr/local/bin/`

```transcript
cat $(which post4)
#! /bin/sh
/work/forth.data/repo/github/post4/src/post4 -c /work/forth.data/repo/github/post4/src/post4.p4 "$@"
```

```transcript
post4 -V
post4/0.12.0  Copyright 2007, 2024 by Anthony Howe. All rights reserved.

BUILT="Thu, 27 Nov 2024 20:11:11 +0000"
CFLAGS=""
LDFLAGS=""
LIBS="-lm"
POST4_PATH=".:/usr/pkg/lib/post4:/usr/local/lib/post4:/usr/lib/post4"

sizeof char=1 short=2 int=4 long=8 size_t=8 intptr_t=8 float=4 double=8
void *=8 long long=8 long double=16 JMP_BUF=200
```

**Comment by ruv** [comment]
This problem with `key?` is not reproduced on Debian, but reproduced on Ubuntu 20.04 in WSL.

Probably, this problem is connected with a terminal 🤔

**Comment by SirWumpus** [comment]
> This problem with `key?` is not reproduced on Debian, but reproduced on Ubuntu 20.04 in WSL.

Eww.  WSL (not WSL, the Waterloo Systems Language I once learned) - if its tied to Windows its probably not 100% POSIX.

* NetBSD 10.0 (VM) worked as shown above.

* Cygwin appears OK.
```
$ ./post4
ok key? dup . [if] key . [then]
0 ok key? dup . [if] key . [then]
0 ok
$ uname -a
CYGWIN_NT-10.0-19045 BEAR 3.5.3-1.x86_64 2024-04-03 17:25 UTC x86_64 Cygwin
$
```

* Rocky Linux (VM) oK
```
roche$ ./post4
ok key? dup . [if] key . [then]
0 ok key? dup . [if] key . [then]
0 ok key? dup . [if] key . [then]
0 ok 
roche$ uname -a
Linux roche 5.14.0-427.22.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 19 17:35:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
roche$ 
```

* I do NOT have WSL and will NOT touch it.  Probably something in the `termios` that is not working as advertised.  Cygwin I found to be great for working with GNU (meh) tools on Windows.

* What about MacOS? 

> Probably, this problem is connected with a terminal 🤔

The human side of the terminal 😎😁 maybe?

**Comment by SirWumpus** [comment]
> Ubuntu 20.04 in WSL.

@ruv Grasping at straws... what does `stty -a` report for Ubuntu under WSL?  Anything out of the ordinary?

**Comment by SirWumpus** [comment]
Please attach the generated `post4/src/config.h` for Ubuntu under WSL.  It might provide a clue.

**Comment by ruv** [comment]
> what does `stty -a` report for Ubuntu under WSL?

```transcript
╰─>$ stty -a
speed 38400 baud; rows 29; columns 120; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = M-^?; eol2 = M-^?; swtch = M-^?; start = ^Q; stop = ^S;
susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

> Please attach the generated `post4/src/config.h`

Attached:
[config.h.txt](https://github.com/user-attachments/files/17950125/config.h.txt)

**Comment by SirWumpus** [comment]
Well nothing obvious jumps out to bite me (not counting the puppy at my feet).

I'll just have to add more error checking when I [tcsetattr()](https://github.com/SirWumpus/post4/blob/62c1f7ab2fae710bfc205d39010e5868f0909269/src/aline.c#L47) to see if it reports a failure.  `Oh the pain and suffering, the inhumanity, the indignity of something or other.`

**Comment by SirWumpus** [comment]
@ruv Please try the test above eg. `KEY? DUP . [IF] KEY . [THEN]` to see if it reports any error.

**Comment by ruv** [comment]
No any error is reported.

```transcript
ok KEY? DUP . [IF] KEY . [THEN]
-1 107 ok
ok KEY? DUP . [IF] KEY . [THEN]
-1 27 ok
ok KEY? DUP . [IF] KEY . [THEN]
-1 32 ok
```

```transcript
╰─>$ post4 -V
post4/0.13.0  Copyright 2007, 2024 by Anthony Howe. All rights reserved.

BUILT="Thu, 28 Nov 2024 16:37:24 +0000"
COMMIT="v0.13.0-18-g5173a50"
CFLAGS=""
LDFLAGS=""
LIBS="-lm"
POST4_PATH=".:/usr/pkg/lib/post4:/usr/local/lib/post4:/usr/lib/post4"

sizeof char=1 short=2 int=4 long=8 size_t=8 intptr_t=8 float=4 double=8
void *=8 long long=8 long double=16 JMP_BUF=200
```

**Comment by SirWumpus** [comment]
Hmm.  Do you have Ubuntu installed else where than WSL?  I'm really starting to think this is a WSL issue, since 4 other environments work correctly, the only odd one is WSL.

Next step would be to write small termios test program or maybe test alternative code using ioctl().  Hard to believe VMIN=0 VTIME=0 mode doesn't work.

**Comment by ruv** [comment]
>  if its tied to Windows its probably not 100% POSIX.

This is a bug in WSL, see: https://github.com/microsoft/WSL/issues/3507

**Comment by ruv** [comment]
A possible workaround is to use `fd_readable(STDIN_FILENO)` (from https://github.com/mawww/kakoune/issues/3112#issuecomment-538183196)

Perhaps, this WSL issue is hardly worth introducing a workaround for.

**Comment by SirWumpus** [comment]
> > if its tied to Windows its probably not 100% POSIX.
> 
> This is a bug in WSL, see: [microsoft/WSL#3507](https://github.com/microsoft/WSL/issues/3507)

Right.  So its WSL problem (as expected).  Is there a WSL update for you to install?


> A possible workaround is to use `fd_readable(STDIN_FILENO)` (from [mawww/kakoune#3112 (comment)](https://github.com/mawww/kakoune/issues/3112#issuecomment-538183196))

The work around requires a C++ header and I suppose a C++ only function.  Post4 is ISO C plus some POSIX and happily C++ free (I dislike C++ as much as I dislike burrs in puppy's hairy legs and paws).

> Perhaps, this WSL issue is hardly worth introducing a workaround for.

I seriously doubt this is worth fixing on my end.  This sort of thing would affect lots of other (Curses) terminal programs.  Don't think its our responsibility.  If [Cygwin](https://cygwin.com/) can make it work and Post4 works fine with Cygwin, but Microsoft as a the OS manufacturer can't get this right, it begs a question.  POSIX termios has been around since at least the 1990s (when Microsoft was trying to bolt on POSIX subsystem to Windows to win NIST based contracts).  At MKS we managed to make a DOS `vi(1)` that was portable and conforming to assorted *nixs (even had some HP block terminal support added).  You'd think after all that time, termios would be a well understood problem.

**Comment by SirWumpus** [comment]
At this point in time, I'm not going to workaround this Microsoft problem of their own making.  I'd need a LOT more users to care about this.

**Comment by ruv** [comment]
> I seriously doubt this is worth fixing on my end. 

Yes, I meant that too.

Just for reference (if somebody will search for this problem), an implementation in Gforth: [engine/io.c # `key_avail`](https://github.com/forthy42/gforth/blob/ea89dc58409c3c45764a7bd530ebe77fc0a3cc2c/engine/io.c#L665).

**Comment by ruv** [comment]
> Is there a WSL update for you to install?

No. All available updates have been installed. As far as I understand, this bug has not yet been fixed.
