### ISSUE TITLE
Broken `traverse-wordlist`

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#88]
Some test cases:
```forth
t{ 0 ' false wordlist traverse-wordlist -> 0 }t
t{ 0 ' false forth-wordlist traverse-wordlist ( 0 nt ) 0<> -> 0 true }t
t{ 0 :noname drop 1+ true ; forth-wordlist traverse-wordlist ( u ) 0 u>  -> true }t
```
Last two cases produce <q>-9 thrown: invalid memory address</q>.

**Comment by SirWumpus** [comment]
Does (or should) `TRAVERSE-WORDLIST` skip `:NONAME` words?

**Comment by ruv** [comment]
Yes, `travarse-wordlist` only enumerates the definitions that have been placed into the word list (and not removed).

A new named definition is formally placed into the compilation word list when it becomes findable in this list; a colon-definition becomes findable on `;` (Semicolon) or on `does>`. An unnamed definition is not placed into the compilation word list at all.

See also: [`TRAVERSE-WORDLIST` must not expose the current definition](https://forth-standard.org/standard/tools/TRAVERSE-WORDLIST?hideDiff#reply-1123).
