### ISSUE TITLE
"Verb-noun" naming convention

### ISSUE THREAD

**Issue by ruv** [SirWumpus/post4#89]
> This is what bugs me.  I always like to name `object+action` (though I admit I'm inconsistent in my C projects) so I can group things by module/package etc and search easily.  But I'm game to try it that way for a while (as long as it doesn't chaff or give me a wedgie).   

 _Originally posted by @SirWumpus in [2664ce4](https://github.com/SirWumpus/post4/commit/2664ce4bb1b78e92143962cf80d124253836b306#r150371664)_

**Comment by SirWumpus** [comment]
So what is this about?  I already renamed source-offset in 94d0e9398.

**Comment by ruv** [comment]
A few more additional comments.

### Consistency

If we have both forms of naming "verb-noun" and "noun-verb",  we should somehow describe what form is used in what case.  Otherwise, we should stick to one form.

Introducing both `set-something` and `something-inc`  looks like inconsistency.

### Naming conventions

Of course, any naming convention may be used in a program, or for system-specific words. But when we standardize a word, its name should follow the naming convention used in standard words.

I would like to standardize the "source" family of words.

### Standard naming

It can be considered that the first part (the first segment without the type prefix if any) of a Forth word name determines the speech part of the whole name. Then for standard **_ordinary_** words (excluding historical exceptions and operators/symbols) the following rules are true:
   - if a word may have side effects, its name is a verb;
   - if a word's name is a noun, the word has no side effects;
   - if a word's name is an adjective (rarely), the word has no side effects;

For example:
- `file-size`, `file-position`, `file-status` are **nouns**;
   - they do not have side effects.
- `resize-file`, `reposition-file`, `delete-file`, `open-file`, `close-file` are **verbs**;
   - they _may_ have side effects.

Note that all the words that contain the same noun "file" as a segment of their names constitute a family of words. This is a kind of namespace. If I were to put this word family into a separate wordlist, I would remove the "file" segment from their names, and the above rules would still apply.

-----

If an _ordinary_ word has no side effect, its name may be a verb, or a noun. If the word is thought of as an action or a series of steps, its name usually is a verb.

Of course, there are a number of exceptions to the general rules among the standard words. For example, the defining words that are nouns are such exceptions. But any new exception must have a convincing basis, I think.

Some standard **_unordinary_** words are adjectives (e.g. `[defined]`), adverbs (e.g. `again`), conjunctions (e.g. `if`), or preposition (e.g. `to`). The above rules do not apply to them.

Some exception (or unusual names) in standard _ordinary_ words:
  - `wordlist` is an ordinary Forth word that may have side effects, whose name is a noun;
  - `thru` is an ordinary Forth word that may have side effects, whose name is a preposition;
  - `within` is an ordinary Forth word without side effects, whose name is a preposition;

In programs, adjective are sometimes used for _ordinary_ words that may have side effects.

Some English words have multiple meanings and be a verb or a noun in different contexts. In a Forth word name, an English word is considered in only one appropriate meaning.

**Comment by SirWumpus** [comment]
Thanks for the very clear explanation (you do that so well, you must be a professor).  By "what is this about?" was more a question about were have I missed doing verb-noun.  I can think of

* `block-open` `block-close` -> `open-block` `close-block`

All the "source" words so far follow your earlier examples from #86, though `source-renaming` (`source-following`) shouldn't it  be `remaining-source`?

Rail siding: I like that Japanese sentences have object-verb structure typically, sometimes a subject-object-verb "Wakarimasu ka?" (thought Japanese conjugate for positive or negative affirmation of the statement, which is tricky because they conjugate more than just the verb).

**Comment by ruv** [comment]
> you do that so well, you must be a professor

This is probably ironic 😉   But thanks anyway!

> So what is this about?

I created this issue to answer on your <q>I always like to name `object+action`</q>, your concerns, and to provide a rationale for the Forth's naming convention (as per my understanding).


>  I can think of
> -    `block-open` `block-close` -> `open-block` `close-block`

I didn't mean that, but yes, I would name them in the form "verb-noun".

-----

> though `source-remaining` (`source-following`) shouldn't it be `remaining-source`?
 
When a Forth word's name has the form "noun1-noun2",  noun2 typically refers to what this word returns.

When a Forth word's name has the form "noun-adjective" or "adjective", this adjective _often_ plays the role of a noun (see _nominalized adjectives_) and also refers to what this word returns.

For example, in the standard [word](https://forth-standard.org/standard/core/UNUSED) `unused ( -- u )`, the adjective "unused" means "the unused part of data space in the dictionary",  which becomes "the unused" (a noun).

Another example is the standard [word](https://forth-standard.org/standard/string/MinusTRAILING) `-trailing ( sd1 -- sd2 )`. This Forth word means "substract-trailing", which is a verb (as a whole) and has the form "verb-adjective".  However, the English word "trailing" in this case serves as a noun "the trailing", which is a nominalized adjective, a short for "the trailing spaces". So, this word actually follows the form "verb-noun".

In the Forth word `source-remaining`,  the English word "remaining" also serves as a noun "the remaining part of the input buffer". Ditto for `source-following` — "following" means "the following part of the input buffer".

Therefore, `source-remaining` shouldn't be `remaining-source`.

-----

BTW, I initially chose `source-following` after XPath, which has the `preceding` and  `following` axes (among others), the former containing the preceding nodes, the later containing the following nodes from the current position.

**Comment by ruv** [comment]
This can be closed, I think.

**Comment by SirWumpus** [comment]
Nothing outstanding in `post4.p4` for the moment?  Yeah!  Friday night party!

**Comment by ruv** [comment]
> Nothing outstanding in `post4.p4` for the moment?

For example, there are words like `_word_set`, `_word_clear`, `_word_bit?` — possible options for them are: `mark-xt-bit ( xt n.bit -- )`, `unmark-xt-bit ( xt n.bit -- )`, `xt-bit ( xt n.bit -- flag )`.

Following the names `depth` and `rdepth`, I would rename `return-stack-cells` to `rstack-cells`  (since "return" is read as a verb).

But I would not worry too much about words that are internal and not documented.

**Comment by SirWumpus** [comment]
> there are words like _word_set, _word_clear, _word_bit?

Wonder if we should fuss with "internal" words not meant for general use.  Though I'd go with `set-word-bit`, `clear-word-bit`, `is-word-bit`.  The names loosely come from the C macros.

>  I would rename `return-stack-cells` to rstack-cells 

`return-stack-cells` is the constant (now variable in Post4) taken from Table 3.5.  Since `return-stack` is term from 2.1 Definitions of terms.  A similar problem if it had been named `call-stack`, though `ip-stack` might have been a good noun, but both trumped by history.

**Comment by ruv** [comment]
> `return-stack-cells` is the constant (now variable in Post4) taken from Table 3.5. Since `return-stack` is term from 2.1 Definitions of terms.

This term is used in prose with a determiner, like "**the** return stack", so "return" in this phrase is a noun that acts as an adjective (a [noun adjunct](https://en.wikipedia.org/wiki/Noun_adjunct)).  

But in programming languages, `return` is typically read as a verb. So, I would interpret a word with the name `return-foo` as `( -- foo never )`, a kind of `exit` that returns something specific to the caller.

Also, if we choose `rdepth` instead of `return-depth`, then **for consistency** we should choose `rstack-cells` instead of `return-stack-cells`.
